/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated/collection'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedCollectionScanRouteImport } from './routes/_authenticated/collection.scan'
import { Route as AuthenticatedCollectionIdRouteImport } from './routes/_authenticated/collection.$id'
import { Route as AuthenticatedCollectionCardCardIdRouteImport } from './routes/_authenticated/collection.card.$cardId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionScanRoute =
  AuthenticatedCollectionScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => AuthenticatedCollectionRoute,
  } as any)
const AuthenticatedCollectionIdRoute =
  AuthenticatedCollectionIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCollectionRoute,
  } as any)
const AuthenticatedCollectionCardCardIdRoute =
  AuthenticatedCollectionCardCardIdRouteImport.update({
    id: '/card/$cardId',
    path: '/card/$cardId',
    getParentRoute: () => AuthenticatedCollectionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/collection': typeof AuthenticatedCollectionRouteWithChildren
  '/search': typeof AuthenticatedSearchRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/u/$slug': typeof USlugRoute
  '/collection/$id': typeof AuthenticatedCollectionIdRoute
  '/collection/scan': typeof AuthenticatedCollectionScanRoute
  '/collection/card/$cardId': typeof AuthenticatedCollectionCardCardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/collection': typeof AuthenticatedCollectionRouteWithChildren
  '/search': typeof AuthenticatedSearchRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/u/$slug': typeof USlugRoute
  '/collection/$id': typeof AuthenticatedCollectionIdRoute
  '/collection/scan': typeof AuthenticatedCollectionScanRoute
  '/collection/card/$cardId': typeof AuthenticatedCollectionCardCardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/collection': typeof AuthenticatedCollectionRouteWithChildren
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/u/$slug': typeof USlugRoute
  '/_authenticated/collection/$id': typeof AuthenticatedCollectionIdRoute
  '/_authenticated/collection/scan': typeof AuthenticatedCollectionScanRoute
  '/_authenticated/collection/card/$cardId': typeof AuthenticatedCollectionCardCardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/collection'
    | '/search'
    | '/watchlist'
    | '/u/$slug'
    | '/collection/$id'
    | '/collection/scan'
    | '/collection/card/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alerts'
    | '/collection'
    | '/search'
    | '/watchlist'
    | '/u/$slug'
    | '/collection/$id'
    | '/collection/scan'
    | '/collection/card/$cardId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/collection'
    | '/_authenticated/search'
    | '/_authenticated/watchlist'
    | '/u/$slug'
    | '/_authenticated/collection/$id'
    | '/_authenticated/collection/scan'
    | '/_authenticated/collection/card/$cardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  USlugRoute: typeof USlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection/scan': {
      id: '/_authenticated/collection/scan'
      path: '/scan'
      fullPath: '/collection/scan'
      preLoaderRoute: typeof AuthenticatedCollectionScanRouteImport
      parentRoute: typeof AuthenticatedCollectionRoute
    }
    '/_authenticated/collection/$id': {
      id: '/_authenticated/collection/$id'
      path: '/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof AuthenticatedCollectionIdRouteImport
      parentRoute: typeof AuthenticatedCollectionRoute
    }
    '/_authenticated/collection/card/$cardId': {
      id: '/_authenticated/collection/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/collection/card/$cardId'
      preLoaderRoute: typeof AuthenticatedCollectionCardCardIdRouteImport
      parentRoute: typeof AuthenticatedCollectionRoute
    }
  }
}

interface AuthenticatedCollectionRouteChildren {
  AuthenticatedCollectionIdRoute: typeof AuthenticatedCollectionIdRoute
  AuthenticatedCollectionScanRoute: typeof AuthenticatedCollectionScanRoute
  AuthenticatedCollectionCardCardIdRoute: typeof AuthenticatedCollectionCardCardIdRoute
}

const AuthenticatedCollectionRouteChildren: AuthenticatedCollectionRouteChildren =
  {
    AuthenticatedCollectionIdRoute: AuthenticatedCollectionIdRoute,
    AuthenticatedCollectionScanRoute: AuthenticatedCollectionScanRoute,
    AuthenticatedCollectionCardCardIdRoute:
      AuthenticatedCollectionCardCardIdRoute,
  }

const AuthenticatedCollectionRouteWithChildren =
  AuthenticatedCollectionRoute._addFileChildren(
    AuthenticatedCollectionRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRouteWithChildren
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedCollectionRoute: AuthenticatedCollectionRouteWithChildren,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  USlugRoute: USlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
